spring:
  main:
    banner-mode: off
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    username: guest
    password: guest
    listener:      simple:        acknowledge-mode: manual
      